---
title: "Readme"
author: "Ryan Meyer"
date: '2022-09-29'
output: pdf_document
---

# Overview

This folder contains the results documents and code to read in, clean, analyze, and graph the data from the summer 2021 decomposition study conducted by Meyer et al., (2022) as part of the USDA Agriculture and Food Research Initiative Competitive Grant No. 2019-69012-29851.

# Folders

## Data

This folder contains raw data that is read into the import and clean script. 

## Folder Archive

Contains folder that are no longer needed or used. 

## Output 

This is where all outputs from importing, cleaning, calculations, and statistical results are stored. Organized by:

- archived output: outputs that are no longer used but may be useful to keep around for reference

- carbon to nitrogen ratios: contains outputs with the carbon to nitrogen ratio calculations

- figures: this is where final figures are saved at high resolution for publication

- final files from import and k calcs

  - from import and clean: cleaned data files from import and clean
  
  - k vales: contains cleaned k value files from 02 calculate k values nonlinear approach
  
- statistical results: summaries of statistical results with estimated marginal means and letter for statistical groupings, these are primarily used for plotting statistical results

## Scripts

Scripts are organized numerically in the order in which they should be run. 

- 01 Imports, cleans, and saves the data into the output folder to calculate the k values in 02.

- 02 "calculate k values nonlinear approach" uses negative exponential nonlinear modeling to calculate the k values for analysis and fitted values for plotting. NOTE: Because different columns were needed for plotting and analysis to calculate and save the values for either plotting or analysis you will need to change the columns specified in the statements that run the nonlinear model. 

- 02 "Carbon to Nitrogen ratios" calculates and saves the carbon to nitrogen ratios as outputs for plotting

- 03 Conducts statistical analysis using generalized linear models to determine the differences in biomass loss, nitrogen mineralization, and carbon minearlization by species and soil type. It then saves relevant values to output for plotting.

- 04 Final figures reads in all relevant files from output for final plotting. Some modifications to data frames are needed for plotting and these modifications are dont at the top of the document. 





